CREATE TABLE EXDATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(300),
    NICKNAME VARCHAR(60),
    TEAMNAME INT,
    GAMEID INT,
    GAMEDATE DATE
);
INSERT INTO EXDATA(DESCRIPTION,NICKNAME,TEAMNAME,GAMEID,GAMEDATE) 
VALUES ("뭐냐","김인봉",1,199744,"2020-05-05");

--mysql -u root -p DB접속
--CREATE DATABASE FOTMOB2; db선택
--USE FOTMOB2
--show databases
DROP TABLE EXDATA;