CREATE TABLE 'EXDATA' (
    'ID' INT PRIMARY KEY,
    'AUTHOR' VARCHAR2(30) NOT NULL,
    'TIME' DATE NOT NULL,
    'DESCRIPTION' VARCHAR(300)
);

INSERT INTO 'EXDATA' VALUES (1,'KYLE','2021-05-11','맨시티VS맨유');
INSERT INTO 'EXDATA' VALUES (2,'METHEW','2021-05-11','토트넘VS첼시');
INSERT INTO 'EXDATA' VALUES (3,'JOHNSON','2021-05-11','아스날VS리버풀');
