CREATE TABLE EXDATA (
    ID INT PRIMARY KEY,
    AUTHOR VARCHAR(30),
    TIME DATE,
    DESCRIPTION VARCHAR(300)
);

INSERT INTO EXDATA VALUES (1,'KYLE','2021-05-11','맨시티 ㅅㅅㅅㅅㅅㅅㅅㅅㅅㅅㅅ');
INSERT INTO EXDATA VALUES (2,'METHEW','2021-05-11','맹구멸망 맹구멸망 맹구멸망');
INSERT INTO EXDATA VALUES (3,'JOHNSON','2021-05-11','페르난지뉴 골골골골골골');

--mysql -u root -p DB접속
--CREATE DATABASE FOTMOB2; db선택
--USE FOTMOB2
--show databases
DROP TABLE EXDATA;